import type { NewsItem } from "./types"

/** News items migrated from the legacy united-studio.com News archive. */
export const newsItems: NewsItem[] = [
  {
    id: "korg-sv-2s-88",
    title: "KORG SV-2S 88導入",
    date: "2026-05-24",
    category: "studio",
    href: "https://united-studio.com/news",
    external: true,
    source: "static",
  },
  {
    id: "akg-c414eb",
    title: "AKG C414EB導入",
    date: "2026-05-04",
    category: "studio",
    href: "https://united-studio.com/news",
    external: true,
    source: "static",
  },
  {
    id: "studio-reservation-url-change",
    title: "スタジオ予約URL変更のお知らせ",
    date: "2026-02-24",
    category: "reserve",
    href: "https://united-studio.com/news",
    external: true,
    source: "static",
  },
  {
    id: "phone-number-change",
    title: "電話番号変更のお知らせ",
    date: "2026-01-27",
    category: "company",
    href: "https://united-studio.com/2026/01/27/120764",
    external: true,
    source: "static",
  },
  {
    id: "neumann-u87",
    title: "Neumann U87導入",
    date: "2025-07-17",
    category: "studio",
    href: "https://united-studio.com/2025/07/17/120737",
    external: true,
    source: "static",
  },
  {
    id: "expo-2025-hamacco-dan-dan",
    title: "2025大阪・関西万博『浜っ鼓★弾★DAN』ステージ演舞",
    date: "2025-05-12",
    category: "yosakoi",
    href: "https://united-studio.com/2025/05/12/120701",
    external: true,
    source: "static",
  },
  {
    id: "neumann-v402-oram-sonics",
    title: "Neumann V402, Oram sonics EQ Comp導入",
    date: "2025-04-22",
    category: "studio",
    href: "https://united-studio.com/2025/04/22/120658",
    external: true,
    source: "static",
  },
  {
    id: "nishikawa-exercise",
    title: "山形県西川町『西川エクササイズ』楽曲提供",
    date: "2024-06-19",
    category: "works",
    href: "https://united-studio.com/2024/06/19/120534",
    external: true,
    source: "static",
  },
  {
    id: "ams-neve-1073dpx",
    title: "AMS Neve 1073DPX導入",
    date: "2024-05-27",
    category: "studio",
    href: "https://united-studio.com/2024/05/27/120503",
    external: true,
    source: "static",
  },
  {
    id: "rupert-neve-shelford-channel",
    title: "Rupert Neve Designs Shelford Channel導入",
    date: "2024-03-25",
    category: "studio",
    href: "https://united-studio.com/2024/03/25/120443",
    external: true,
    source: "static",
  },
  {
    id: "cassina-lc5-sofa",
    title: "Cassina LC5 ソファー",
    date: "2024-02-22",
    category: "studio",
    href: "https://united-studio.com/2024/02/22/120420",
    external: true,
    source: "static",
  },
  {
    id: "dspeaker-anti-mode-2-dual-core",
    title: "DSPeaker Anti-Mode 2.0 Dual- Core導入",
    date: "2023-12-12",
    category: "studio",
    href: "https://united-studio.com/2023/12/12/120361",
    external: true,
    source: "static",
  },
]
