export type NewsCategory =
  | "company"
  | "studio"
  | "utattemita"
  | "yosakoi"
  | "reserve"
  | "works"
  | "info"
  | "release"
  | "event"

export type NewsItem = {
  id: string
  title: string
  date: string // ISO 8601 (YYYY-MM-DD)
  category: NewsCategory
  /** Link target. Use an absolute URL for external posts, a path for internal pages. */
  href: string
  /** True when href is an external URL. Defaults to false. */
  external?: boolean
  /** Slug for future internal detail pages. */
  slug: string
  /** Static body paragraphs migrated from the legacy News archive. */
  body: string[]
  /** Sanitized WordPress body generated by the management command. */
  contentHtml?: string
  /** Plain-text summary generated from the WordPress excerpt. */
  excerpt?: string
  /** WordPress modification timestamp used by metadata and sitemap. */
  modifiedAt?: string
  /** Featured media stays on the dedicated CMS host during this migration. */
  featuredImage?: {
    src: string
    alt: string
    width?: number
    height?: number
  }
  wpId?: number
  wpSlug?: string
  originalPath?: string
  /** Legacy article URL retained for migration reference only. */
  originalUrl?: string
  /** Identifies the data origin for debugging / cache invalidation. */
  source?: "static" | "wordpress"
}

export type ImportedNewsItem = {
  wpId: number
  wpSlug: string
  title: string
  publishedAt: string
  modifiedAt: string
  excerpt: string
  contentHtml: string
  category: NewsCategory
  wpCategoryIds: number[]
  newSlug: string
  newUrl: string
  originalUrl: string
  originalPath: string
  featuredImage: NonNullable<NewsItem["featuredImage"]>
}

/**
 * Adapter interface for news sources.
 * TOP and the News index consume the same static source through this interface.
 */
export interface NewsSource {
  getLatestNews(limit?: number): Promise<NewsItem[]>
  getNewsList(): Promise<NewsItem[]>
}
